import http from 'node:http';
import {chromium} from 'playwright';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {discover,scan,validURL,createSession,confirmSession,closeSession,sessions,LIMITS} from './src/scanner.js';
const PORT=Number(process.env.PORT||4190),jobs=new Map(),root=fileURLToPath(new URL('.',import.meta.url));
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value))}
async function body(req){let b='';for await(const chunk of req){b+=chunk;if(b.length>20000000)throw Error('Request too large.')}try{return JSON.parse(b||'{}')}catch{throw Error('Invalid JSON request.')}}
function target(raw){const url=validURL(raw),u=new URL(url);if(['localhost','127.0.0.1','[::1]'].includes(u.hostname)&&u.port===String(PORT))throw Error('Choose a target website, not the ImageLens workspace.');return url;}
const server=http.createServer(async(req,res)=>{try{const host=req.headers.host||'';if(![`127.0.0.1:${PORT}`,`localhost:${PORT}`].includes(host))return json(res,403,{error:'Local connections only.'});const u=new URL(req.url,`http://${host}`);if(req.headers.origin&&!['http://127.0.0.1:'+PORT,'http://localhost:'+PORT].includes(req.headers.origin))return json(res,403,{error:'Cross-origin access denied.'});if(u.pathname.startsWith('/api/')&&!['GET','HEAD'].includes(req.method)&&req.headers['x-imagelens']!=='1')return json(res,403,{error:'Missing local request header.'});
 if(u.pathname==='/api/pdf'&&req.method==='POST'){const data=await body(req);if(typeof data.html!=='string')throw Error('Report HTML is required.');const browser=await chromium.launch({headless:true});try{const context=await browser.newContext({javaScriptEnabled:false});await context.route('**/*',route=>route.abort());const page=await context.newPage();await page.setContent(data.html,{waitUntil:'domcontentloaded',timeout:20000});const pdf=await page.pdf({format:'A4',printBackground:true,margin:{top:'15mm',bottom:'15mm',left:'10mm',right:'10mm'}});res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="imagelens-report.pdf"'});res.end(pdf);}finally{await browser.close()}return;}
 if(u.pathname==='/api/health')return json(res,200,{ok:true,version:'1.1.0',limits:LIMITS});
 if(u.pathname==='/api/sessions'&&req.method==='POST'){const data=await body(req);return json(res,201,await createSession(target(data.url)))}
 const sessionMatch=u.pathname.match(/^\/api\/sessions\/([\w-]+)(\/confirm)?$/);if(sessionMatch){if(req.method==='DELETE'){await closeSession(sessionMatch[1]);return json(res,200,{ok:true})}if(req.method==='POST'&&sessionMatch[2])return json(res,200,await confirmSession(sessionMatch[1]));return json(res,405,{error:'Unsupported method.'})}
 if(u.pathname==='/api/jobs'&&req.method==='POST'){const data=await body(req);data.url=target(data.url);if(!['discover','scan'].includes(data.kind))throw Error('Unknown job type.');if(data.requestId){if(!/^[a-f0-9-]{36}$/i.test(data.requestId))throw Error('Invalid request identity.');const existing=jobs.get(data.requestId);if(existing){if(existing.requestKey!==JSON.stringify([data.kind,data.url,data.sessionId||null,data.scope||'',data.pages?.map(target)||null]))throw Error('This request identity belongs to a different audit.');return json(res,200,{id:existing.id});}}if([...jobs.values()].filter(j=>j.status==='running').length>=2)return json(res,429,{error:'Two browser jobs are already running. Wait or cancel one.'});if(data.kind==='scan'){if(!Array.isArray(data.pages)||!data.pages.length||data.pages.length>LIMITS.pages)throw Error(`Choose between 1 and ${LIMITS.pages} pages.`);data.pages=data.pages.map(target);if(data.pages.some(p=>new URL(p).origin!==new URL(data.url).origin))throw Error('All pages must belong to the target website.');}if(data.sessionId&&!sessions.has(data.sessionId))throw Error('Sign-in session expired. Please sign in again.');for(const[id,j]of jobs)if(j.status!=='running'&&jobs.size>=20)jobs.delete(id);const controller=new AbortController();const job={id:data.requestId||randomUUID(),requestKey:JSON.stringify([data.kind,data.url,data.sessionId||null,data.scope||'',data.pages?.map(target)||null]),status:'running',gaps:[],progress:{message:'Starting browser…',done:0,total:0},signal:controller.signal,controller};jobs.set(job.id,job);json(res,202,{id:job.id});(async()=>{try{const result=await(data.kind==='discover'?discover:scan)(data,job);if(!job.signal.aborted){job.result=result;job.status='complete'}}catch(e){if(!job.signal.aborted){job.error=e.message;job.status='error'}}finally{if(job.signal.aborted)job.status='cancelled';}})();return;}
 const m=u.pathname.match(/^\/api\/jobs\/([\w-]+)$/);if(m){const job=jobs.get(m[1]);if(!job)return json(res,404,{error:'This job expired. Start again.'});if(req.method==='DELETE'){job.controller.abort();job.status='cancelled';await job.browser?.close().catch(()=>{});return json(res,200,{ok:true})}if(req.method==='GET')return json(res,200,{id:job.id,status:job.status,progress:job.progress,error:job.error,...(job.status==='complete'?{result:job.result}:{})});}
 const files={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/styles.css':'styles.css','/lens-tokens.css':'lens-tokens.css','/theme.js':'theme.js','/brand/imagelens-mark.svg':'brand/imagelens-mark.svg','/assets/fonts/geist-latin.woff2':'assets/fonts/geist-latin.woff2'};if(!files[u.pathname]||req.method!=='GET')return json(res,404,{error:'Not found.'});const file=files[u.pathname];res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.woff2')?'font/woff2':'text/html','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"});res.end(await readFile(root+file));
 }catch(e){json(res,400,{error:e.message||'Request failed.'})}});
server.listen(PORT,'127.0.0.1',()=>console.log(`ImageLens running at http://127.0.0.1:${PORT}`));
async function shutdown(){for(const j of jobs.values())if(j.status==='running'){j.controller.abort();await j.browser?.close().catch(()=>{})}for(const id of sessions.keys())await closeSession(id);server.close(()=>process.exit(0));}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
