import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),base='http://127.0.0.1:4295';
const server=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'4295'},stdio:'pipe'});
const out=new URL('../test-output/design/',import.meta.url);await mkdir(out,{recursive:true});let browser;const checks=[],errors=[];
const check=label=>{checks.push(label);console.log('PASS '+label)};
try{
 for(let i=0;i<60;i++){try{if((await fetch(base+'/api/health')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);
 const axe=await readFile(require.resolve('axe-core/axe.min.js'),'utf8');
 const accessible=async label=>{await page.waitForTimeout(200);await page.evaluate(axe);const r=await page.evaluate(()=>globalThis.axe.run());assert.deepEqual(r.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),[],label);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label+' overflow');check(label)};
 for(const theme of ['light','dark']){await page.locator('#theme-select').selectOption(theme);for(const [width,height] of [[1440,1050],[375,812],[844,390]]){await page.setViewportSize({width,height});await accessible(`home ${theme} ${width}`);await page.screenshot({path:new URL(`home-${theme}-${width}.png`,out).pathname,fullPage:true})}}
 await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');const other=await context.newPage();await other.goto(base);await page.locator('#theme-select').selectOption('light');await other.waitForFunction(()=>document.documentElement.dataset.theme==='light');check('Theme persists and synchronizes across tabs');await other.close();
 await page.locator('#theme-select').selectOption('system');await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');check('System theme follows OS and supports reduced motion');
 await page.locator('#home-url').fill('ftp://example.com');await page.locator('#home-audit-form button').click();assert.match(await page.locator('#home-url-error').innerText(),/HTTP/);await page.locator('#home-url').fill('https://example.com/gallery');await page.locator('#home-audit-form button').click();assert.equal(await page.locator('#site-url').inputValue(),'https://example.com/gallery');await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'New audit',exact:true}).click();assert.equal(await page.locator('#site-url').inputValue(),'');await page.getByRole('button',{name:'Close dialog'}).click();check('Invalid URL, deliberate URL handoff, fresh New audit');
 const result=JSON.parse(await readFile(new URL('../test-output/report.json',import.meta.url),'utf8'));assert.ok(result.assets.some(a=>a.preview?.startsWith('data:image/png;base64,')),'Actual scanner captured previews');await page.evaluate(a=>localStorage.setItem('imagelens-audits-v1',JSON.stringify([a])),result);await page.reload();await page.getByRole('button',{name:'Audit overview',exact:true}).click();
 for(const theme of ['light','dark']){await page.locator('#theme-select').selectOption(theme);for(const [width,height] of [[1440,1050],[375,812],[844,390]]){await page.setViewportSize({width,height});await accessible(`report ${theme} ${width}`);await page.screenshot({path:new URL(`report-${theme}-${width}.png`,out).pathname,fullPage:true})}}
 await page.locator('#status-filter').selectOption('all');assert.ok(await page.locator('.asset-preview img').count()>0);await page.locator('#viewport-filter').selectOption('Mobile');assert.ok((await page.locator('.asset-top').allTextContents()).every(t=>t.includes('Mobile')));await page.locator('#finding-search').fill('NO_SUCH_IMAGE');assert.equal(await page.locator('.asset-card').count(),0);await page.getByRole('button',{name:'Clear filters',exact:true}).click();await page.getByRole('button',{name:'List view',exact:true}).click();assert.ok(await page.locator('tbody tr').count()>0);await page.getByRole('button',{name:'Gallery view',exact:true}).click();check('Real previews, viewport filtering, empty-state recovery, gallery/list switching');
 await page.setViewportSize({width:375,height:812});await page.locator('[data-detail]').first().click();await accessible('mobile image inspector');await page.screenshot({path:new URL('inspector-mobile.png',out).pathname,fullPage:true});await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').evaluate(d=>d.open),false);await page.setViewportSize({width:1440,height:1050});await page.locator('[data-detail]').first().click();await accessible('desktop image inspector');await page.screenshot({path:new URL('inspector-desktop.png',out).pathname,fullPage:true});await page.keyboard.press('Escape');
 await page.getByRole('tab',{name:'Overview',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.equal(await page.getByRole('tab',{name:/^All images/}).getAttribute('aria-selected'),'true');check('Keyboard report tabs and dismissible inspector');
 await page.getByRole('button',{name:'Home',exact:true}).click();await page.locator('[data-history]').first().click();assert.ok(await page.locator('.asset-gallery').count());await page.getByRole('button',{name:'Scan history',exact:true}).click();await accessible('scan history');check('Home recents and scan history navigation');
 await page.getByRole('button',{name:'Home',exact:true}).click();await page.setViewportSize({width:375,height:812});await page.evaluate(()=>{const sizes=[...document.querySelectorAll('body *')].map(e=>[e,parseFloat(getComputedStyle(e).fontSize)]);for(const [e,size] of sizes)e.style.fontSize=(size*2)+'px'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:new URL('home-enlarged-text.png',out).pathname,fullPage:true});check('200% text at 375px');
 assert.deepEqual(errors,[]);assert.equal((await fetch(base+'/brand/imagelens-mark.svg')).status,200);assert.equal((await fetch(base+'/assets/fonts/geist-latin.woff2')).status,200);check('No browser errors, local icon/font served');await writeFile(new URL('results.json',out),JSON.stringify({checks},null,2));
}finally{await browser?.close();server.kill('SIGTERM')}
