import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {fixture} from './fixture.mjs';
import {writeFile,mkdir} from 'node:fs/promises';
const site=await fixture(4294),base='http://127.0.0.1:4293';const server=spawn(process.execPath,['server.js'],{cwd:new URL('..',import.meta.url),env:{...process.env,IMAGELENS_TEST_HEADLESS:'1',PORT:'4293'},stdio:'pipe'});let browser;const findings=[];
async function ready(){for(let i=0;i<60;i++){try{await fetch(base+'/api/health');return}catch{await new Promise(r=>setTimeout(r,100))}}throw Error('No server')}
async function start(page){await page.getByRole('button',{name:'New audit',exact:true}).last().click();await page.locator('#site-url').fill(site.url+'/second');await page.locator('#next').click();await page.getByRole('radio',{name:'Current page'}).check();await page.locator('#next').click();const response=page.waitForResponse(r=>r.url()===base+'/api/jobs'&&r.request().method()==='POST');await page.locator('#next').click();return(await(await response).json()).id}
async function finished(page){await page.waitForFunction(()=>!document.querySelector('dialog').open,null,{timeout:60000})}
try{await ready();browser=await chromium.launch();const context=await browser.newContext();const page=await context.newPage();await page.goto(base);const id=await start(page);await page.reload();const restored=await page.locator('#scan-stage').count();let completed;for(let i=0;i<100;i++){const j=await(await fetch(base+'/api/jobs/'+id)).json();if(j.status==='complete'){completed=true;break}await new Promise(r=>setTimeout(r,150))}await page.waitForFunction(()=>JSON.parse(localStorage.getItem('imagelens-audits-v1')||'[]').length===1,null,{timeout:10000});let persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('imagelens-audits-v1')||'[]').length);findings.push({scenario:'Refresh during a running scan',status:restored&&persisted?'passed':'observed failure',evidence:{restoredProgress:!!restored,serverCompleted:completed,savedReportCount:persisted}});
await context.clearCookies();await page.evaluate(()=>localStorage.clear());await page.reload();const second=await context.newPage();await second.goto(base);await start(page);await finished(page);await start(second);await finished(second);const count=await page.evaluate(()=>JSON.parse(localStorage.getItem('imagelens-audits-v1')||'[]').length);findings.push({scenario:'Two tabs finish separate audits',status:count===2?'passed':'observed failure',evidence:{expectedReports:2,actualReports:count}});
const quota=await context.newPage();await quota.goto(base);await quota.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='imagelens-audits-v1')throw new DOMException('Quota exceeded','QuotaExceededError');return original.call(this,k,v)}});await start(quota);await finished(quota);let warning=await quota.getByText(/storage is full|not saved|could not be saved/i).count();findings.push({scenario:'Browser storage fills when audit finishes',status:warning?'passed':'observed failure',evidence:{persistentWarningVisible:!!warning,visibleStatus:await quota.locator('#toast').innerText()}});
const interrupted=await context.newPage();await interrupted.goto(base);let interruptions=0;await interrupted.route('**/api/jobs/*',async route=>{if(route.request().method()==='GET'&&interruptions<2){interruptions++;await route.abort()}else await route.continue()});await start(interrupted);await finished(interrupted);findings.push({scenario:'Brief polling connection loss',status:(await interrupted.locator('.site-info').count())?'passed':'observed failure',evidence:{droppedPolls:interruptions,recoveredReport:await interrupted.locator('.metric strong').first().innerText()}});
const late=await context.newPage();await late.goto(base);await late.route('**/api/jobs',async route=>{if(route.request().method()==='POST'){const response=await route.fetch();await new Promise(r=>setTimeout(r,800));await route.fulfill({response})}else await route.continue()});const lateStart=start(late);await late.waitForSelector('#scan-stage');await late.getByRole('button',{name:'Cancel',exact:true}).click();const lateId=await lateStart;await late.waitForTimeout(600);const lateState=await(await fetch(base+'/api/jobs/'+lateId)).json();findings.push({scenario:'Cancel before start confirmation arrives',status:lateState.status==='cancelled'?'passed':'observed failure',evidence:{serverJobStatus:lateState.status,progressDialogOpen:await late.locator('dialog[open]').count()}});
const expired=await context.newPage();await expired.goto(base);await expired.getByRole('button',{name:'New audit',exact:true}).last().click();await expired.locator('#site-url').fill(site.url+'/account');await expired.getByRole('radio',{name:'Requires sign-in'}).check();const sessionResponse=expired.waitForResponse(r=>r.url()===base+'/api/sessions');await expired.getByRole('button',{name:'Open sign-in browser'}).click();const session=(await(await sessionResponse).json());await expired.getByRole('button',{name:'Confirm completed sign-in'}).click();await expired.locator('#next').click();await expired.getByRole('radio',{name:'Current page'}).check();await expired.locator('#next').click();await fetch(base+'/api/sessions/'+session.id,{method:'DELETE',headers:{'X-ImageLens':'1'}});await expired.locator('#next').click();await expired.getByRole('button',{name:'Back to setup'}).click();const recovered=await expired.getByRole('button',{name:'Open sign-in browser'}).count();findings.push({scenario:'Sign-in expires after scope selection',status:recovered?'passed':'observed failure',evidence:{reconnectAvailable:!!recovered,preservedURL:await expired.locator('#site-url').inputValue()}});await expired.getByRole('button',{name:'Close dialog'}).click();
await mkdir(new URL('../test-output/',import.meta.url),{recursive:true});await writeFile(new URL('../test-output/scenario-audit.json',import.meta.url),JSON.stringify(findings,null,2));console.log(JSON.stringify(findings,null,2));if(process.env.EXPECT_FIXED==='1')assert.ok(findings.every(x=>x.status==='passed'));}finally{await browser?.close();server.kill('SIGTERM');site.server.closeAllConnections();await new Promise(r=>site.server.close(r))}
