import { chromium } from 'playwright';
import { randomUUID } from 'node:crypto';
import { checkLogin } from './authentication.js';

export const LIMITS={pages:200,queue:3000,scrolls:24,interactions:16,states:18,timeout:20000,resourceTimeout:7000};
export const sessions=new Map();
const unsafe=/\b(?:add[-_ ]?to[-_ ]?cart|remove|delete|destroy|reset|submit|save|send|buy|purchase|pay|checkout|subscribe|unsubscribe|upload|download|log[-_ ]?out|sign[-_ ]?out)\b/i;
export function validURL(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Use an HTTP or HTTPS URL without embedded credentials.');u.hash=/^#(?:\/|!)/.test(u.hash)?u.hash:'';return u.href}
function actionURL(raw){try{const u=new URL(raw);return unsafe.test(u.pathname)||['action','do','cmd','operation'].some(k=>unsafe.test(u.searchParams.get(k)||''))}catch{return true}}
function cancelled(signal){if(signal?.aborted)throw Error('Audit cancelled.');}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function gap(job,page,reason,detail=''){const key=page+'|'+reason+'|'+detail;if(!job.gaps.some(x=>x.key===key))job.gaps.push({key,page,reason,detail});}
async function guard(context,job){await context.unroute('**/*');await context.route('**/*',async route=>{const req=route.request();if(!['GET','HEAD','OPTIONS'].includes(req.method())||actionURL(req.url())){gap(job,new URL(req.url()).origin+new URL(req.url()).pathname,'Blocked action request',req.method());await route.abort().catch(()=>{});}else await route.continue().catch(()=>{});});}
export async function createSession(url){url=validURL(url);const browser=await chromium.launch({headless:process.env.IMAGELENS_TEST_HEADLESS==='1'});try{const context=await browser.newContext({viewport:{width:1366,height:900}});const page=await context.newPage();await page.goto(url,{waitUntil:'domcontentloaded',timeout:LIMITS.timeout}).catch(e=>{if(!e.message.includes('Timeout'))throw e;});const id=randomUUID();const session={id,browser,context,page,url,confirmed:false,busy:false,lastUsed:Date.now()};sessions.set(id,session);browser.on('disconnected',()=>sessions.delete(id));return{id,url:page.url()}}catch(e){await browser.close();throw e}}
export async function confirmSession(id){const s=sessions.get(id);if(!s||s.page.isClosed())throw Error('The sign-in window was closed or expired. Open a new session.');const result=await checkLogin(s.page,{loginUrl:s.url},new URL(s.url).origin);if(!result.accepted)throw Error(result.message);s.confirmed=true;s.lastUsed=Date.now();return{confirmed:true,url:s.page.url()}}
export async function closeSession(id){const s=sessions.get(id);sessions.delete(id);await s?.browser.close().catch(()=>{});}
setInterval(()=>{for(const [id,s] of sessions)if(!s.busy&&Date.now()-s.lastUsed>30*60*1000)closeSession(id)},60000).unref();

async function acquire(input,job){let s;if(input.sessionId){s=sessions.get(input.sessionId);if(!s?.confirmed)throw Error('Your sign-in session has expired. Sign in again.');if(s.busy)throw Error('This browser session is already running an audit.');if(new URL(input.url).origin!==new URL(s.url).origin)throw Error('The signed-in session belongs to a different website.');s.busy=true;s.lastUsed=Date.now();}else{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1366,height:900}});s={browser,context,page:await context.newPage(),private:false};}job.browser=s.browser;await guard(s.context,job);return s;}
async function release(s,input){if(!s)return;if(input.sessionId){s.busy=false;s.lastUsed=Date.now();}else await s.browser.close().catch(()=>{});}
async function navigate(page,url){if(page.url()!==url){const response=await page.goto(url,{waitUntil:'domcontentloaded',timeout:LIMITS.timeout});page._imageLensResponse={url,status:response?.status()||0};}if(page._imageLensResponse?.url===url&&page._imageLensResponse.status>=400)throw Error('Page returned HTTP '+page._imageLensResponse.status);await page.waitForLoadState('networkidle',{timeout:1800}).catch(()=>{});}
async function links(page,origin){return page.evaluate(origin=>[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(h=>{try{return new URL(h).origin===origin}catch{return false}}),origin)}
async function scrollPage(page,job,url){let exhausted=false;for(let i=0;i<LIMITS.scrolls;i++){cancelled(job.signal);const atEnd=await page.evaluate(()=>{window.scrollBy(0,Math.max(400,innerHeight*.8));return scrollY+innerHeight>=document.documentElement.scrollHeight-3});await delay(130);if(atEnd){const still=await page.evaluate(()=>scrollY+innerHeight>=document.documentElement.scrollHeight-3);if(still){exhausted=true;break;}}}if(!exhausted)gap(job,url,'Scroll limit reached','Lazy or infinite content may remain undiscovered.');await page.evaluate(()=>scrollTo(0,0));}
export async function discover(input,job){let s;try{s=await acquire(input,job);const origin=new URL(input.url).origin,queue=[input.url],seen=new Set(),pages=[];while(queue.length&&seen.size<LIMITS.pages){cancelled(job.signal);const url=queue.shift();if(seen.has(url))continue;seen.add(url);job.progress={message:`Discovering pages: ${seen.size}`,done:seen.size,total:seen.size+queue.length};try{await navigate(s.page,url);if(new URL(s.page.url()).origin!==origin){gap(job,url,'Redirected outside website');continue;}await scrollPage(s.page,job,url);pages.push({url,path:new URL(url).pathname+new URL(url).search+new URL(url).hash,title:await s.page.title()});for(const raw of await links(s.page,origin)){let h;try{h=validURL(raw)}catch{continue}if(!seen.has(h)&&!queue.includes(h)&&!actionURL(h)){if(queue.length<LIMITS.queue)queue.push(h);else gap(job,input.url,'Discovery queue limit reached');}}}catch(e){cancelled(job.signal);gap(job,url,'Page could not be discovered',e.message.split('\n')[0]);}}if(queue.length)gap(job,input.url,'Page discovery limit reached',`${queue.length} queued pages remain; limit ${LIMITS.pages}.`);return{pages,gaps:job.gaps,complete:false,limits:LIMITS};}finally{await release(s,input)}}

// Executed within each frame. Traverses open shadow roots and retains every occurrence.
async function collect(frame){return frame.evaluate(()=>{
 const nodes=[];function walk(root,prefix=''){for(const el of root.querySelectorAll('*')){nodes.push({el,prefix});if(el.shadowRoot)walk(el.shadowRoot,prefix+selector(el)+' >>> ');}}function selector(el){if(el.id)return '#'+CSS.escape(el.id);let parts=[];for(let n=el;n&&n.nodeType===1;n=n.parentElement){let part=n.tagName.toLowerCase();if(n.id){parts.unshift('#'+CSS.escape(n.id));break}let siblings=n.parentElement?[...n.parentElement.children].filter(x=>x.tagName===n.tagName):[];if(siblings.length>1)part+=`:nth-of-type(${siblings.indexOf(n)+1})`;parts.unshift(part);}return parts.join(' > ')}walk(document);
 const out=[];const refs=(el,attr)=>(el.getAttribute(attr)||'').split(/\s+/).filter(Boolean).map(id=>(el.getRootNode().getElementById?.(id)||document.getElementById(id))?.textContent||'').join(' ').trim();
 function base(el,prefix,type,source){const style=getComputedStyle(el),r=el.getBoundingClientRect();const hidden=!!el.closest('[hidden],[aria-hidden="true"],[inert]')||style.display==='none'||style.visibility==='hidden'||r.width===0||r.height===0;let parent=el.closest('a,button,[role="button"],[role="link"]');const accessible=el.getAttribute('aria-label')||refs(el,'aria-labelledby')||el.querySelector(':scope > title')?.textContent||'';return{selector:prefix+selector(el),type,source,alt:el.getAttribute('alt'),title:el.getAttribute('title')||'',accessibleName:accessible,hidden,decorative:el.getAttribute('alt')===''||['presentation','none'].includes(el.getAttribute('role')),functional:!!parent,parentName:parent?(parent.getAttribute('aria-label')||refs(parent,'aria-labelledby')||parent.innerText||'').trim():'',width:r.width,height:r.height,naturalWidth:el.naturalWidth||0,naturalHeight:el.naturalHeight||0,complete:!!el.complete,loading:el.getAttribute('loading')||'',html:el.outerHTML.slice(0,1500),describedBy:refs(el,'aria-describedby'),tooltip:el.getAttribute('title')||refs(el,'aria-describedby'),dpr:devicePixelRatio}}
 for(const{el,prefix}of nodes){if(el.matches('img,input[type="image"]')){const source=el.currentSrc||el.src||'';const row=base(el,prefix,el.tagName==='INPUT'?'Image input':'IMG',source);row.preview=null;try{if(el.tagName==='IMG'&&el.complete&&el.naturalWidth>0){const c=document.createElement('canvas');const scale=Math.min(1,320/el.naturalWidth,220/el.naturalHeight);c.width=Math.max(1,Math.round(el.naturalWidth*scale));c.height=Math.max(1,Math.round(el.naturalHeight*scale));c.getContext('2d').drawImage(el,0,0,c.width,c.height);const preview=c.toDataURL('image/png');if(preview.length<160000)row.preview=preview;}}catch{}row.variants=[];const sets=[el.getAttribute('srcset'),...el.closest('picture')?.querySelectorAll('source')||[]].map(x=>typeof x==='string'?x:x?.getAttribute('srcset')).filter(Boolean);for(const set of sets){if(set.includes('data:')){row.variantParseGap=true;continue;}for(const item of set.split(',')){let value=item.trim().split(/\s+/)[0];try{row.variants.push(new URL(value,document.baseURI).href)}catch{}}}if(el.src&&el.src!==source)row.variants.push(el.src);out.push(row)}else if(el.tagName.toLowerCase()==='svg'&&!el.ownerSVGElement){out.push(base(el,prefix,'Inline SVG',''));}
 for(const pseudo of [null,'::before','::after']){const bg=getComputedStyle(el,pseudo).backgroundImage;if(bg&&bg!=='none'){const matches=[...bg.matchAll(/url\(["']?(.*?)["']?\)/g)];for(const m of matches){try{const row=base(el,prefix,'CSS background',new URL(m[1],document.baseURI).href);row.selector+=pseudo||'';out.push(row)}catch{}}}}
 }
 return out;
})}
function finding(code,severity,message,fix){return{code,severity,message,fix}}
function validate(a){const f=[];if(a.source&&(!a.loaded||a.httpStatus>=400))f.push(finding(a.timedOut?'image-timeout':'image-load-failed',a.timedOut?'unverified':'broken',a.timedOut?'Image verification timed out.':`Image did not load or decode${a.httpStatus?' (HTTP '+a.httpStatus+')':''}.`,'Check the resource URL, access permissions and image encoding, then retry.'));if(!a.source&&a.type!=='Inline SVG')f.push(finding('empty-source','broken','Image has no usable source.','Provide a valid image source.'));
 if(!a.hidden){if(['IMG','Image input'].includes(a.type)){if(a.alt===null&&!a.accessibleName)f.push(finding('missing-alt','alt','No image text alternative is present.','Add contextual alt text; use alt="" only for a decorative image.'));if(a.functional&&!a.parentName&&!a.accessibleName&&!a.alt)f.push(finding('unnamed-image-control','alt','The image link or button has no accessible name.','Name the action or destination on the image or enclosing control.'));if(a.alt&&/^(image|photo|picture|img|untitled|\S+\.(png|jpg|jpeg|webp|gif))$/i.test(a.alt.trim()))f.push(finding('generic-alt','review','The alternative may not describe the image’s purpose.','Review surrounding content and write a meaningful alternative.'));if(a.alt===''&&!a.functional)f.push(finding('decorative-review','review','Empty alt marks this image as decorative.','Confirm that the image communicates no information needed to understand the page.'));if(a.alt&&a.alt.length>180)f.push(finding('long-alt','review','Long text alternative needs contextual review.','Use a concise alternative and adjacent longer description when appropriate.'));}if(a.type==='Inline SVG'&&!a.accessibleName&&!a.decorative)f.push(finding('svg-name-review','review','Inline SVG has no explicit text alternative.','Determine whether this graphic is decorative; otherwise supply an accessible name.'));if(a.type==='CSS background')f.push(finding('background-purpose','review','CSS backgrounds have no native alt attribute.','Confirm the image is decorative or that equivalent information exists in text.'));}
 if(a.title&&!a.alt&&!a.accessibleName&&!a.hidden&&a.type==='IMG')f.push(finding('tooltip-only','alt','A title tooltip is the only text supplied for this image.','Supply a reliable image alternative; do not use a hover tooltip as the only description.'));
 if(a.bytes>500000)f.push(finding('large-download','performance',`Image transfer exceeds 500 KB (${Math.round(a.bytes/1000)} KB).`,'Compress the image and serve a suitably sized responsive variant.'));
 if(a.loaded&&a.width>0&&a.naturalWidth>0&&a.width*a.dpr>a.naturalWidth*1.5)f.push(finding('low-resolution','performance','The source may be too small for its rendered size and pixel density.','Provide a higher-resolution source variant.'));
 if(a.variantParseGap)f.push(finding('srcset-unparsed','unverified','A data-URL srcset could not be fully enumerated.','Inspect additional responsive candidates manually.'));
 for(const v of a.variantResults||[])if(!v.loaded)f.push(finding('variant-failed',v.timedOut?'unverified':'broken',`Responsive candidate ${v.timedOut?'timed out':'failed to decode'}: ${v.url}`,'Correct the candidate URL and retest at the corresponding breakpoint.'));
 return f;
}
async function probe(frame,url,cache,network){if(!url)return{loaded:false};if(cache.has(url))return cache.get(url);const p=frame.evaluate(({url,timeout})=>new Promise(resolve=>{let im=new Image(),done=false;const finish=value=>{if(done)return;done=true;clearTimeout(timer);resolve(value)};let timer=setTimeout(()=>{im.src='';finish({loaded:false,timedOut:true})},timeout);im.onload=async()=>{try{await im.decode();finish({loaded:im.naturalWidth>0,naturalWidth:im.naturalWidth,naturalHeight:im.naturalHeight})}catch{finish({loaded:false})}};im.onerror=()=>finish({loaded:false});im.src=url}),{url,timeout:LIMITS.resourceTimeout}).catch(()=>({loaded:false,timedOut:true})).then(value=>({...value,...network.get(url)}));cache.set(url,p);return p;}
async function snapshots(page,job,url,viewport,assets,seen,cache,network,state){let count=0;for(const [fi,frame]of page.frames().entries()){cancelled(job.signal);let rows;try{rows=await collect(frame)}catch(e){gap(job,url,'Frame could not be inspected',frame.url());continue}for(let i=0;i<rows.length;i+=6){cancelled(job.signal);const batch=await Promise.all(rows.slice(i,i+6).map(async a=>{const key=[url,viewport,fi,a.selector,a.source,a.alt,a.accessibleName,a.title,a.hidden].join('|');if(seen.has(key))return null;seen.add(key);const verification=a.type==='Inline SVG'?{loaded:true}:await probe(frame,a.source,cache,network);const variants=[...new Set(a.variants||[])].filter(v=>v!==a.source);const variantResults=[];for(const v of variants)variantResults.push({url:v,...await probe(frame,v,cache,network)});let asset={...a,...verification,id:randomUUID(),page:url,frame:frame.url(),viewport,state,bytes:verification.bytes||0,variantResults,name:a.source?(()=>{try{return decodeURIComponent(new URL(a.source).pathname.split('/').pop())||'Image resource'}catch{return'Embedded image'}})():'Inline SVG'};asset.issues=validate(asset);asset.status=['broken','alt','unverified','review','performance'].find(k=>asset.issues.some(f=>f.severity===k))||'pass';delete asset.variants;return asset}));for(const a of batch)if(a){assets.push(a);count++;}}
 }return count;}
async function controls(page){return page.evaluate(()=>[...document.querySelectorAll('summary,[role="tab"],button[aria-expanded],button[aria-label]')].map((e,index)=>({index,name:e.getAttribute('aria-label')||e.textContent||'',tag:e.tagName,role:e.getAttribute('role'),expanded:e.getAttribute('aria-expanded'),selected:e.getAttribute('aria-selected'),form:!!e.closest('form'),visible:!!e.getClientRects().length})).filter(e=>e.visible&&!e.form&&e.expanded!=='true'&&e.selected!=='true'))}
export async function scan(input,job){let s,responseListener;const start=Date.now(),assets=[],pageResults=[],seen=new Set();try{s=await acquire(input,job);const urls=[...new Set(input.pages.map(validURL))];const network=new Map();responseListener=response=>{const h=response.headers();if(response.request().resourceType()==='image')network.set(response.url(),{httpStatus:response.status(),mime:h['content-type']||'',bytes:Number(h['content-length'])||0})};s.context.on('response',responseListener);for(let pi=0;pi<urls.length;pi++){const url=urls[pi];for(const viewport of [{name:'Desktop',width:1366,height:900},{name:'Mobile',width:390,height:844}]){cancelled(job.signal);job.progress={message:`Inspecting ${new URL(url).pathname} · ${viewport.name}`,done:pi*2+(viewport.name==='Mobile'?1:0),total:urls.length*2,images:assets.length};let entry={url,viewport:viewport.name,status:'checked',images:0,states:0};pageResults.push(entry);try{await s.page.setViewportSize(viewport);await navigate(s.page,url);if(new URL(s.page.url()).origin!==new URL(input.url).origin){gap(job,url,'Page redirected outside selected website');entry.status='unverified';continue;}if(await s.page.locator('input[type="password"]:visible').count()){gap(job,url,'Sign-in required','Protected content was not inspected.');entry.status='unverified';continue}await scrollPage(s.page,job,url);const cache=new Map();entry.images+=await snapshots(s.page,job,url,viewport.name,assets,seen,cache,network,'Initial page');entry.states++;let actions=await controls(s.page);let eligible=actions.filter(c=>!unsafe.test(c.name)&&(c.tag==='SUMMARY'||c.role==='tab'||c.expanded==='false'||/^(next|previous|show|view).*(image|slide|photo)|^(next|previous)$/i.test(c.name.trim())));if(eligible.length>LIMITS.interactions)gap(job,url,'Interaction limit reached',`${eligible.length-LIMITS.interactions} candidate controls not explored.`);for(const control of eligible.slice(0,LIMITS.interactions)){cancelled(job.signal);try{const loc=s.page.locator('summary,[role="tab"],button[aria-expanded],button[aria-label]').nth(control.index);await loc.click({timeout:1500});await delay(220);if(s.page.url()!==url){gap(job,url,'Interaction navigated to another page',control.name.slice(0,150));await navigate(s.page,url);continue;}await scrollPage(s.page,job,url);entry.images+=await snapshots(s.page,job,url,viewport.name,assets,seen,cache,network,control.name.trim().slice(0,100)||'Expanded content');entry.states++;}catch(e){gap(job,url,'Interaction could not be inspected',control.name.slice(0,150));}}
 const residual=await s.page.locator('canvas,iframe,button,[role="button"]').count();if(residual)gap(job,url,'Additional interaction or embedded content may exist','Forms, unrecognized controls, closed shadow roots, canvas semantics, and exhaustive gallery journeys require manual review.');
 }catch(e){cancelled(job.signal);entry.status='unverified';gap(job,url,'Page inspection failed',e.message.split('\n')[0]);}}}
 const counted=new Set(assets.map(a=>a.page+'|'+a.frame+'|'+a.selector+'|'+a.source));return{id:randomUUID(),date:new Date().toISOString(),durationMs:Date.now()-start,url:input.url,access:input.sessionId?'private':'public',scope:input.scope||'Selected pages',pages:urls,assets,pageResults,unverified:job.gaps.length,sampleData:false,coverage:{complete:false,discoveredOccurrences:assets.length,elementOccurrences:counted.size,uniqueResources:new Set(assets.map(a=>a.source).filter(Boolean)).size,gaps:job.gaps,limits:LIMITS,note:'Every discovered occurrence was evaluated. Counts include viewport-specific observations. A checked page does not imply every possible state was discovered.'}};
 }finally{if(s&&responseListener)s.context.off('response',responseListener);await release(s,input)}}
